version: '3.8'

services:
  opensecureconf-admin:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    container_name: opensecureconf-admin
    ports:
      - "9080:80"
    environment:
      - OSC_BASE_URL=${OSC_BASE_URL:-http://localhost:9000}
      - OSC_USER_KEY=123456789-user-key
      - OSC_API_KEY=123456789-api-key
    restart: unless-stopped
    networks:
      - opensecureconf-network

networks:
  opensecureconf-network:
    driver: bridge
